[package]
name = "namada_governance"
description = "Namada governance"
resolver = "2"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
testing = ["proptest"]

[dependencies]
namada_core = { path = "../core" }
namada_macros = {path = "../macros"}
namada_parameters = {path = "../parameters"}
namada_storage = {path = "../storage"}
namada_trans_token = {path = "../trans_token"}

borsh.workspace = true
itertools.workspace = true
proptest = { workspace = true, optional = true }
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true


[dev-dependencies]
namada_core = {path = "../core", default-features = false, features = ["testing"]}

proptest.workspace = true
